name: Deploy Loan API

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build & Start Docker
        run: docker-compose up -d --build

      - name: Sleep for Container Startup
        run: sleep 20

      - name: Stop Docker
        run: docker-compose down
